version: '3.8'
services:
  devcontainer:
    container_name: polis-devcontainer
    image: polis-devcontainer:latest
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    ports:
      - 8000:8000

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../database/migrations:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: polis
      POSTGRES_USER: polis
      POSTGRES_DB: polis
    ports:
      - 5432:5432

volumes:
  postgres-data: